export type Role = 'participant' | 'educator' | 'admin';
export type Profile = { id: string; role: Role; display_name: string | null; suspended: boolean; approved: boolean; logo_url: string | null; created_at: string };
export type Hunt = { id: string; owner_id: string; class_id?: string|null; title: string; description: string | null; status: 'draft'|'active'|'archived'; invite_code: string; points: number; instructions: string|null; link1: string|null; link2: string|null; created_at: string };
export type Challenge = { id: string; hunt_id: string; title: string; prompt: string | null; answer: string | null; points: number; order_idx: number };
export type Team = { id: string; hunt_id: string; name: string; score: number; created_at: string };
export type Membership = { hunt_id: string; user_id: string; joined_at: string };
export type Submission = { id: string; challenge_id: string; team_id: string | null; user_id: string; answer: string | null; status: 'pending'|'approved'|'rejected'; reviewed_by: string | null; created_at: string };
export type AuditEntry = { id: number; actor_id: string | null; action: string; target_type: string | null; target_id: string | null; meta: any; created_at: string };
export type User = { id: string; email?: string; role: Role; display_name?: string };
